### ISSUE TITLE
SyntaxError thrown from Slack's response

### ISSUE THREAD

**Issue by shubear** [adrey/slack-file-upload-action#17]
The following error is thrown after the action completes an upload to slack. The upload doesn't fail as we can see the file on Slack. However the build is marked as a failure due to the exception.

```
2022-01-26T17:42:41.5017375Z SyntaxError: Unexpected token s in JSON at position 0
2022-01-26T17:42:41.5017828Z     at JSON.parse (<anonymous>)
2022-01-26T17:42:41.5018799Z     at IncomingMessage.<anonymous> (/home/runner/work/_actions/adrey/slack-file-upload-action/master/dist/index.js:77:37)
2022-01-26T17:42:41.5019420Z     at IncomingMessage.emit (events.js:215:7)
2022-01-26T17:42:41.5019905Z     at endReadableNT (_stream_readable.js:1184:12)
2022-01-26T17:42:41.5020451Z     at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This is how we define the action

```
      - name: Upload apk to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: build/${{ matrix.targetPlatform }}/Panda_${{ steps.build-time.outputs.formattedTime }}.apk
          channel: external-panda-builds
          initial_comment: "${{github.event_name}} on ${{github.ref_name}}@<https://github.com/OrgName/RepoName/commit/${{github.sha}}|${{github.sha}}> by ${{github.actor}}"
```

**Comment by adrey** [comment]
Could you please reproduce it in postman?
![screen](https://user-images.githubusercontent.com/1103095/151313273-51608c47-b461-4360-924e-6af80e2ce52e.jpg)

Seems that you receive non-json response from slack, wonder how it's possible
https://api.slack.com/methods/files.upload

**Comment by JackFlukinger** [comment]
I'm also having this same problem @adrey , started happening this morning for no apparent reason.

**Comment by kalkun** [comment]
Experienced this too

**Comment by felixwoestmann** [comment]
Experiencing the same error. Receiving a 'stream timeout' message.
Seems to happen in conjunction with larger filesizes for debug builds.

`stream timeout
^

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/adrey/slack-file-upload-action/master/dist/index.js:77:37)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by adrey** [comment]
According this thread https://github.com/slackapi/python-slack-sdk/issues/1165 it's a server-side issue

**Comment by ashwin-nath-m** [comment]
received this same error

**Comment by DavidAmunga** [comment]
Anyone able to resolve this.

**Comment by Ehadam** [comment]
Getting this error as well.  Any update?

**Comment by Ehadam** [comment]
![PXwYOhPMZD](https://user-images.githubusercontent.com/12561210/166336448-a6685598-b696-4ca1-820c-289fcc6ae082.png)

Also having this problem.  Doesn't seem to happen if I upload a very similar file through Postman.

Any thoughts?

**Comment by okshrey** [comment]
Workaround - Add `continue-on-error: true` in the workflow step.

[Reference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)

**Comment by luizppa** [comment]
Having the same problem here.

> Workaround - Add `continue-on-error: true` in the workflow step.
> 
> [Reference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)

I feel like this is the only possible "solution" right now, however I do not think it is ideal to ignore erros on the whole step. Is there anything we can contribute to help solve the problem?

**Comment by adrey** [comment]
According this thread https://github.com/slackapi/python-slack-sdk/issues/1165 possible workaround is to throttle file transfer speed.

**Comment by chrisedington** [comment]
I also have this problem - any ideas for a fix apart from `continue-on-error: true` ?

**Comment by chrisedington** [comment]
Looks like the https://github.com/slackapi/python-slack-sdk/issues/1165 issue has been closed and merged.

**Comment by StefanOltmann** [comment]
Error still happens.

**Comment by StefanOltmann** [comment]
I now use the official Slack Java SDK directly to do this and it still has that error. So for now this is a problem on Slacks end.

**Comment by StefanOltmann** [comment]
Maybe using the new FileUploadV2 request API will solve this.

**Comment by RossRH** [comment]
> Maybe using the new FileUploadV2 request API will solve this.

I think so. Slack team mentioned it as a solution. Investigated this a bit after the error started happening for our CI. Our internet got upgraded and I guess slack did not want to deal with the faster upload speed. Replicated it with curl, then added `--limit-rate 1M` and the error stopped.

#25 seems related. Im also uploading a zip file but I presume its more an issue with large files on faster connections than anything related to zip files themselves?

FYI: `continue-on-error: true` did indeed continue on error. But the file upload does not complete.
