### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by broblond** [adrey/slack-file-upload-action#21]
I try to download my .apk file to slack and last 2 mounths have this error. 
My token is valid, files in directories. But problem don't fix. 
First time i think it's on my side problem, but i fixed all problems in my android build and upload problem stay with me

Run adrey/slack-file-upload-action@master
undefined:1
stream timeout
^

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/ulfdalen/actions-runner/_work/_actions/adrey/slack-file-upload-action/master/dist/index.js:77:37)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:[12](https://github.com/cryptopay-dev/android/runs/6108423113?check_suite_focus=true#step:10:12)41:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by broblond** [comment]
https://github.com/adrey/slack-file-upload-action/issues/17
