### ISSUE TITLE
cannot upload zip file to slack channel, other files works

### ISSUE THREAD

**Issue by testliomandeep** [adrey/slack-file-upload-action#25]
with:
    token: ***
    path: results.zip
    channel: random
    filetype: zip
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat 'results.zip'
Emitted 'error' event on FormData instance at:
    at FormData.module.exports.660.FormData._error (/home/runner/work/_actions/adrey/slack-file-upload-action/master/dist/index.js:[3](https://github.com/testliomandeep/mytestrepo/actions/runs/3276543032/jobs/5392719402#step:13:3)107:10)
    at FormData.<anonymous> (/home/runner/work/_actions/adrey/slack-file-upload-action/master/dist/index.js:307[5](https://github.com/testliomandeep/mytestrepo/actions/runs/3276543032/jobs/5392719402#step:13:5):[12](https://github.com/testliomandeep/mytestrepo/actions/runs/3276543032/jobs/5392719402#step:13:13))

**Comment by cagatayisikcoda** [comment]
Is there any update or workaround for this ?

**Comment by StefanOltmann** [comment]
Posting a ZIP file to Slack worked for me, but there was still an error.

```
undefined:1
stream timeout
^

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/runner/work/.github/actions/slack-file-upload-action/dist/index.js:77:37)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by StefanOltmann** [comment]
Uploading a ZIP worked for me, but I got the error mentioned in issue #17 after.
